services:
    app.user_type:
        class: "AppBundle\\Form\\UserType"
        tags:
            - { name: form.type }
    app.group_type:
        class: "AppBundle\\Form\\GroupType"
        tags:
            - { name: form.type }
